// <auto-generated />
using System;
using CvProjekt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CvProjekt.Migrations
{
    [DbContext(typeof(CvContext))]
    [Migration("20251226223607_ResetAndSeed")]
    partial class ResetAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CvProjekt.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Education");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DegreeName = "Civilingenjör",
                            Description = "Datateknik",
                            EndYear = 2020,
                            ResumeId = 1,
                            SchoolName = "KTH",
                            StartYear = 2015
                        },
                        new
                        {
                            Id = 2,
                            DegreeName = "Frontend",
                            Description = "YH-utbildning",
                            EndYear = 2021,
                            ResumeId = 2,
                            SchoolName = "Nackademin",
                            StartYear = 2019
                        },
                        new
                        {
                            Id = 3,
                            DegreeName = "Ekonomi",
                            Description = "Master",
                            EndYear = 2014,
                            ResumeId = 3,
                            SchoolName = "Handels",
                            StartYear = 2010
                        },
                        new
                        {
                            Id = 4,
                            DegreeName = "PhD CS",
                            Description = "Forskning",
                            EndYear = 2019,
                            ResumeId = 4,
                            SchoolName = "MIT",
                            StartYear = 2015
                        },
                        new
                        {
                            Id = 5,
                            DegreeName = "Teknik",
                            Description = "Student",
                            EndYear = 2024,
                            ResumeId = 5,
                            SchoolName = "Gymnasiet",
                            StartYear = 2021
                        });
                });

            modelBuilder.Entity("CvProjekt.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = "user-1",
                            Read = true,
                            Text = "Tjena Anna! Snygg frontend du byggde.",
                            ToUserId = "user-2"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = "user-2",
                            Read = false,
                            Text = "Tack Erik! Behöver hjälp med API:et dock.",
                            ToUserId = "user-1"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FromUserId = "user-3",
                            Read = false,
                            Text = "Hej David, söker du jobb?",
                            ToUserId = "user-5"
                        });
                });

            modelBuilder.Entity("CvProjekt.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Byggde en butik",
                            GithubLink = "github.com/erik/shop",
                            Language = "C#",
                            Title = "E-handel",
                            UserId = "user-1",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            Description = "Min hemsida",
                            GithubLink = "github.com/anna/me",
                            Language = "React",
                            Title = "Portfolio",
                            UserId = "user-2",
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Description = "AI budgetering",
                            GithubLink = "github.com/sara/cash",
                            Language = "Python",
                            Title = "BudgetApp",
                            UserId = "user-4",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("CvProjekt.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Qualifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "SQL Server",
                            ResumeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "JavaScript",
                            ResumeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "React",
                            ResumeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Scrum",
                            ResumeId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Python",
                            ResumeId = 4
                        },
                        new
                        {
                            Id = 7,
                            Name = "Machine Learning",
                            ResumeId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "HTML",
                            ResumeId = 5
                        });
                });

            modelBuilder.Entity("CvProjekt.Models.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Resumes");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        });
                });

            modelBuilder.Entity("CvProjekt.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("ProfileVisits")
                        .HasColumnType("int");

                    b.Property<int?>("ResumeId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ResumeId")
                        .IsUnique()
                        .HasFilter("[ResumeId] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-1",
                            AccessFailedCount = 0,
                            Adress = "Storgatan 1",
                            ConcurrencyStamp = "static-concurrency-stamp-user-1",
                            Email = "erik@mail.com",
                            EmailConfirmed = true,
                            FirstName = "Erik",
                            ImgUrl = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
                            IsActive = true,
                            LastName = "Svensson",
                            LockoutEnabled = false,
                            NormalizedEmail = "ERIK@MAIL.COM",
                            NormalizedUserName = "ERIK@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELg7Xy0k9/8Q7k6Xy0k9/8Q7k6Xy0k9/8Q7k6Xy0k9/8Q7k6Xy==",
                            PhoneNumberConfirmed = false,
                            ProfileVisits = 0,
                            ResumeId = 1,
                            SecurityStamp = "static-security-stamp-user-1",
                            TwoFactorEnabled = false,
                            UserName = "erik@mail.com"
                        },
                        new
                        {
                            Id = "user-2",
                            AccessFailedCount = 0,
                            Adress = "Sveavägen 10",
                            ConcurrencyStamp = "static-concurrency-stamp-user-2",
                            Email = "anna@mail.com",
                            EmailConfirmed = true,
                            FirstName = "Anna",
                            ImgUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
                            IsActive = true,
                            LastName = "Lind",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANNA@MAIL.COM",
                            NormalizedUserName = "ANNA@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELg7Xy0k9/8Q7k6Xy0k9/8Q7k6Xy0k9/8Q7k6Xy0k9/8Q7k6Xy==",
                            PhoneNumberConfirmed = false,
                            ProfileVisits = 0,
                            ResumeId = 2,
                            SecurityStamp = "static-security-stamp-user-2",
                            TwoFactorEnabled = false,
                            UserName = "anna@mail.com"
                        },
                        new
                        {
                            Id = "user-3",
                            AccessFailedCount = 0,
                            Adress = "Hamngatan 4",
                            ConcurrencyStamp = "static-concurrency-stamp-user-3",
                            Email = "johan@mail.com",
                            EmailConfirmed = true,
                            FirstName = "Johan",
                            ImgUrl = "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200",
                            IsActive = true,
                            LastName = "Ek",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHAN@MAIL.COM",
                            NormalizedUserName = "JOHAN@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELg7Xy0k9/8Q7k6Xy0k9/8Q7k6Xy0k9/8Q7k6Xy0k9/8Q7k6Xy==",
                            PhoneNumberConfirmed = false,
                            ProfileVisits = 0,
                            ResumeId = 3,
                            SecurityStamp = "static-security-stamp-user-3",
                            TwoFactorEnabled = false,
                            UserName = "johan@mail.com"
                        },
                        new
                        {
                            Id = "user-4",
                            AccessFailedCount = 0,
                            Adress = "Skolgatan 55",
                            ConcurrencyStamp = "static-concurrency-stamp-user-4",
                            Email = "sara@mail.com",
                            EmailConfirmed = true,
                            FirstName = "Sara",
                            ImgUrl = "https://images.unsplash.com/photo-1573496359-0933d2768d98?w=200",
                            IsActive = true,
                            LastName = "Berg",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA@MAIL.COM",
                            NormalizedUserName = "SARA@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELg7Xy0k9/8Q7k6Xy0k9/8Q7k6Xy0k9/8Q7k6Xy0k9/8Q7k6Xy==",
                            PhoneNumberConfirmed = false,
                            ProfileVisits = 0,
                            ResumeId = 4,
                            SecurityStamp = "static-security-stamp-user-4",
                            TwoFactorEnabled = false,
                            UserName = "sara@mail.com"
                        },
                        new
                        {
                            Id = "user-5",
                            AccessFailedCount = 0,
                            Adress = "Studentvägen 3",
                            ConcurrencyStamp = "static-concurrency-stamp-user-5",
                            Email = "david@mail.com",
                            EmailConfirmed = true,
                            FirstName = "David",
                            ImgUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
                            IsActive = false,
                            LastName = "Nordin",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAVID@MAIL.COM",
                            NormalizedUserName = "DAVID@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELg7Xy0k9/8Q7k6Xy0k9/8Q7k6Xy0k9/8Q7k6Xy0k9/8Q7k6Xy==",
                            PhoneNumberConfirmed = false,
                            ProfileVisits = 0,
                            ResumeId = 5,
                            SecurityStamp = "static-security-stamp-user-5",
                            TwoFactorEnabled = false,
                            UserName = "david@mail.com"
                        });
                });

            modelBuilder.Entity("CvProjekt.Models.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Works");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Volvo",
                            Description = "Backend C#",
                            EndDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Position = "Utvecklare",
                            ResumeId = 1,
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Spotify",
                            Description = "Jobbar med webbspelaren",
                            Position = "Frontend Dev",
                            ResumeId = 2,
                            StartDate = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "IKEA",
                            Description = "Ledde IT-team",
                            EndDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Position = "Chef",
                            ResumeId = 3,
                            StartDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Google",
                            Description = "AI forskning",
                            Position = "Data Analyst",
                            ResumeId = 4,
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CvProjekt.Models.Education", b =>
                {
                    b.HasOne("CvProjekt.Models.Resume", "Resume")
                        .WithMany("EducationList")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("CvProjekt.Models.Message", b =>
                {
                    b.HasOne("CvProjekt.Models.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CvProjekt.Models.User", "ToUser")
                        .WithMany("Messages")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("CvProjekt.Models.Project", b =>
                {
                    b.HasOne("CvProjekt.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CvProjekt.Models.Qualification", b =>
                {
                    b.HasOne("CvProjekt.Models.Resume", "Resume")
                        .WithMany("Qualifications")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("CvProjekt.Models.User", b =>
                {
                    b.HasOne("CvProjekt.Models.Resume", "Resume")
                        .WithOne("User")
                        .HasForeignKey("CvProjekt.Models.User", "ResumeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("CvProjekt.Models.Work", b =>
                {
                    b.HasOne("CvProjekt.Models.Resume", "Resume")
                        .WithMany("WorkList")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CvProjekt.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CvProjekt.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CvProjekt.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CvProjekt.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CvProjekt.Models.Resume", b =>
                {
                    b.Navigation("EducationList");

                    b.Navigation("Qualifications");

                    b.Navigation("User")
                        .IsRequired();

                    b.Navigation("WorkList");
                });

            modelBuilder.Entity("CvProjekt.Models.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
